import { Inter } from 'next/font/google'
import './globals.css'
import Navbar3 from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Chirag's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-bgbg"}>
        <Navbar3/>
        {children}
      </body>
    </html>
  )
}
